name: Build client and release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and build client
        run: |
          npm install
          npm run build
      - name: Push back to repo
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected - proceeding with commit and push."
            git config --global user.name 'SystemInternal'
            git config --global user.email 'githubActions@system.com'
            git commit -am "Build js client files"
            git push
          else
            echo "No changes to commit, working tree clean. Skipping commit and push."
          fi
      - name: Run semantic release
        run: |
          npm install @semantic-release/commit-analyzer
          npm install @semantic-release/git
          npm install @semantic-release/github
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
